# Generated by Django 2.2.7 on 2019-11-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('language', models.CharField(max_length=50)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
