# Generated by Django 2.2.7 on 2019-11-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='books_in_collection',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Books in Collection'),
        ),
    ]
