# Generated by Django 2.2.7 on 2019-11-12 11:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Book Title')),
                ('pages', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('published_on', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('genre', models.CharField(choices=[('adventure', 'Adventure'), ('history', 'History'), ('fiction', 'Fiction'), ('nonfiction', 'Non-Fiction')], max_length=50)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authors.Author')),
            ],
        ),
    ]
