# Generated by Django 2.2.7 on 2019-11-07 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Book Title')),
                ('author', models.CharField(max_length=100)),
                ('pages', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('published_on', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('genre', models.CharField(choices=[('adventure', 'Adventure'), ('history', 'History'), ('fiction', 'Fiction'), ('nonfiction', 'Non-Fiction')], max_length=50)),
            ],
        ),
    ]
