# Generated by Django 2.2.8 on 2020-01-16 11:29

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20191209_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_src',
            field=models.FileField(blank=True, null=True, upload_to=books.models.upload_book, verbose_name='Book Source'),
        ),
    ]
