# Generated by Django 2.2.7 on 2019-11-19 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.SmallIntegerField(verbose_name='Age')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50, verbose_name='Gender')),
                ('phone_no', models.CharField(max_length=50, verbose_name='Phone no.')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('district', models.CharField(max_length=50, verbose_name='District')),
                ('language_know', models.CharField(max_length=50, verbose_name='Languages Known')),
                ('occupation', models.CharField(max_length=50, verbose_name='Occupation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
